/* PepTalk 3.0 — Step 6: Dose History organization.
 * Read-only DOM enhancement around React-owned dose history.
 * No MutationObserver and no direct health-data mutation.
 */
const hText=n=>String(n?.textContent||'').replace(/\s+/g,' ').trim();const hLower=n=>hText(n).toLowerCase();
function hActive(){return hText(document.querySelector('.peptalk-bottom-nav .ui-tab-active span')).toLowerCase()||'summary'}
function hScope(){return document.querySelector('.app-frame')||document.querySelector('.app-shell')}
function hRead(){try{const v=JSON.parse(localStorage.getItem('health-injection-entries')||'[]');return Array.isArray(v)?v:[]}catch{return[]}}
function hIsoToday(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function hDaysAgo(n){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-n);return d}
function hFindRow(button){let node=button?.parentElement;for(let i=0;i<5&&node;i++,node=node.parentElement){if(node.querySelector?.('button[title="Edit"]')&&node.querySelector?.('button[title="Delete"]'))return node}return null}
function hDateTokens(iso){if(!iso)return[];const d=new Date(`${iso}T12:00:00`);if(Number.isNaN(d.getTime()))return[iso];return[iso,d.toLocaleDateString('en-US',{month:'short',day:'numeric'}),d.toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}),d.toLocaleDateString('en-US')].map(x=>String(x).toLowerCase())}
function hMatchEntry(row,entries,used){const text=hLower(row);for(const e of entries){if(used.has(e.id))continue;const med=String(e.type||'').toLowerCase();const dose=String(e.dose??'').toLowerCase();const dates=hDateTokens(e.date);if(med&&text.includes(med)&&(!dose||text.includes(dose))&&(dates.some(t=>text.includes(t))||!e.date)){used.add(e.id);return e}}return null}
function hDecorate(scope){const entries=hRead().slice().sort((a,b)=>`${b.date||''} ${b.time||''}`.localeCompare(`${a.date||''} ${a.time||''}`));const used=new Set();const editButtons=Array.from(scope.querySelectorAll('button[title="Edit"]'));const rows=[];editButtons.forEach(btn=>{const row=hFindRow(btn);if(!row||rows.includes(row))return;rows.push(row);row.classList.add('pt-v3-dose-row');const entry=hMatchEntry(row,entries,used);if(entry){row.dataset.ptDate=entry.date||'';row.dataset.ptSearch=`${entry.type||''} ${entry.dose??''} ${entry.unit||''} ${entry.route||''} ${entry.site||''} ${entry.notes||''}`.toLowerCase();if(entry.vialId&&!row.querySelector('.pt-v3-history-source')){const target=btn.closest('div')?.previousElementSibling||row.firstElementChild;const chip=document.createElement('span');chip.className='pt-v3-history-source';chip.textContent='Linked vial';target?.appendChild(chip)}}else{row.dataset.ptSearch=hLower(row)}});return rows}
function hRename(scope){const heading=Array.from(scope.querySelectorAll('h2')).find(n=>hText(n)==='Doses');if(heading){heading.textContent='History';const sub=heading.parentElement?.querySelector('p');if(sub)sub.textContent='Search, review and edit recorded administrations.'}const context=document.querySelector('.page-context');if(context&&hText(context).toLowerCase()==='dose history')context.textContent='History'}
function hIntro(scope){if(scope.querySelector('.pt-v3-history-intro'))return;const heading=Array.from(scope.querySelectorAll('h2')).find(n=>hText(n)==='History'||hText(n)==='Doses');const anchor=heading?.parentElement?.parentElement||scope.firstElementChild;if(!anchor)return;const intro=document.createElement('section');intro.className='pt-v3-history-intro';intro.innerHTML='<div><div class="pt-v3-history-eyebrow">HISTORY</div><div class="pt-v3-history-title">Every administration, easy to find</div><div class="pt-v3-history-copy">Search by compound, dose, route or notes. Edit and delete stay within thumb reach on iPhone.</div></div>';anchor.insertAdjacentElement('afterend',intro)}
function hApply(rows,controls){const query=controls.querySelector('.pt-v3-history-search')?.value.trim().toLowerCase()||'';const range=controls.dataset.range||'all';const today=hIsoToday();const cutoff7=hDaysAgo(6);const cutoff30=hDaysAgo(29);let visible=0;rows.forEach(row=>{const search=(row.dataset.ptSearch||hLower(row));const date=row.dataset.ptDate||'';let inRange=true;if(range==='today')inRange=date===today;else if((range==='7d'||range==='30d')&&date){const d=new Date(`${date}T12:00:00`);inRange=d>=(range==='7d'?cutoff7:cutoff30)}const show=(!query||search.includes(query))&&inRange;row.classList.toggle('pt-v3-history-hidden',!show);if(show)visible++});const count=controls.parentElement?.querySelector('.pt-v3-history-count');if(count)count.textContent=`${visible} ${visible===1?'record':'records'} shown`;const empty=controls.parentElement?.querySelector('.pt-v3-history-empty');if(empty)empty.hidden=visible!==0}
function hControls(scope,rows){let controls=scope.querySelector('.pt-v3-history-controls');if(!controls){const intro=scope.querySelector('.pt-v3-history-intro');if(!intro)return;controls=document.createElement('div');controls.className='pt-v3-history-controls';controls.dataset.range='all';controls.innerHTML='<input class="pt-v3-history-search" type="search" inputmode="search" autocomplete="off" placeholder="Search history"><div class="pt-v3-history-range"><button type="button" data-range="today">Today</button><button type="button" data-range="7d">7D</button><button type="button" data-range="30d">30D</button><button type="button" data-range="all" class="is-active">All</button></div>';const count=document.createElement('div');count.className='pt-v3-history-count';const empty=document.createElement('div');empty.className='pt-v3-history-empty';empty.hidden=true;empty.textContent='No dose records match this view.';intro.insertAdjacentElement('afterend',controls);controls.insertAdjacentElement('afterend',count);count.insertAdjacentElement('afterend',empty);controls.querySelector('input')?.addEventListener('input',()=>hApply(rows,controls));controls.querySelector('.pt-v3-history-range')?.addEventListener('click',e=>{const b=e.target.closest('button[data-range]');if(!b)return;controls.dataset.range=b.dataset.range;controls.querySelectorAll('button[data-range]').forEach(x=>x.classList.toggle('is-active',x===b));hApply(rows,controls)})}hApply(rows,controls)}
function hBuild(){const page=hActive();document.documentElement.dataset.ptMainPage=page;if(page!=='injections')return;const scope=hScope();if(!scope)return;hRename(scope);hIntro(scope);const rows=hDecorate(scope);hControls(scope,rows)}
let hTimer=0;function hSchedule(delay=100){clearTimeout(hTimer);hTimer=setTimeout(()=>requestAnimationFrame(hBuild),delay)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>hSchedule(180),{once:true});else hSchedule(120);[450,1100].forEach(d=>setTimeout(hBuild,d));window.addEventListener('pageshow',()=>hSchedule(80));document.addEventListener('visibilitychange',()=>{if(!document.hidden)hSchedule(100)});document.addEventListener('click',e=>{if(e.target.closest('.peptalk-bottom-nav')||e.target.closest('button[title="Edit"]')||e.target.closest('button[title="Delete"]'))hSchedule(140)},{capture:true});
